<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>false</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <CodeAnalysisRuleSet>..\..\codestyle.tests.ruleset</CodeAnalysisRuleSet>
        <AssemblyName>Mcrio.Finbuckle.MultiTenant.RavenDb.Store.Tests</AssemblyName>
        <RootNamespace>Mcrio.Finbuckle.MultiTenant.RavenDb.Store.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="3.0.2">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.4">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="RavenDB.TestDriver" Version="6.2.3" />
        <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="7.1.0" />
        <PackageReference Include="Moq" Version="4.20.72" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Mcrio.Finbuckle.Multitenant.RavenDb.Store\Mcrio.Finbuckle.Multitenant.RavenDb.Store.csproj" />
    </ItemGroup>

</Project>
